type = "agent"

functions = ["aws-s3"]
models = ["sandbox-openai"]

[env]
AWS_BUCKET = "$AWS_BUCKET"

QDRANT_URL = "$QDRANT_URL"
QDRANT_COLLECTION_NAME = "$QDRANT_COLLECTION_NAME"
QDRANT_EMBEDDING_MODEL = "$QDRANT_EMBEDDING_MODEL"
QDRANT_API_KEY = "${secrets.QDRANT_API_KEY}"
